# vi: ts=2 sw=2 et:

extraction:
  cpp:
    prepare:
      # package list copied from .github/workflows/check.yml
      packages:
        - libglib2.0
        - attr
        - automake
        - gettext
        - autopoint
        - bison
        - dbus
        - gtk-doc-tools
        - libfuse-dev
        - libarchive-dev
        - libcap-dev
        - libattr1-dev
        - libdw-dev
        - libelf-dev
        - python3-pyparsing
        - libjson-glib-dev
        - shared-mime-info
        - desktop-file-utils
        - libpolkit-agent-1-dev
        - libpolkit-gobject-1-dev
        - libseccomp-dev
        - libsoup2.4-dev
        - libsystemd-dev
        - libxml2-utils
        - libgpgme11-dev
        - gobject-introspection
        - libgirepository1.0-dev
        - libappstream-glib-dev
        - libdconf-dev
        - socat
        - libdbus-1-dev
        - libzstd-dev
        - xmlto
        - valgrind
        # needed to build ostree
        - e2fslibs-dev
    after_prepare:
      # Install ostree since lgtm uses an outdated version of ostree
      - git clone https://github.com/ostreedev/ostree.git
      - cd ostree
      - git checkout v2020.8
      - git submodule update --init
      - env NOCONFIGURE=1 ./autogen.sh
      - env BASH_COMPLETIONSDIR=${HOME}/.local/bashcomp ./configure --prefix=${HOME}/.local --with-systemdsystemunitdir=${HOME}/.local/systemdunits --with-systemdsystemgeneratordir=${HOME}/.local/systemdgenerator LDFLAGS=-L${HOME}/.local/lib
      - make
      - make install
      - export PKG_CONFIG_PATH=${HOME}/.local/lib/pkgconfig
      - export LD_LIBRARY_PATH=${HOME}/.local/lib
    configure:
      command:
        - echo $LD_LIBRARY_PATH
        - cat $LD_LIBRARY_PATH/libostree-1.la
        - ./autogen.sh
        - ./configure
