# vi: ts=2 sw=2 et:

extraction:
  cpp:
    prepare:
      # package list copied from .github/workflows/check.yml
      packages:
        - libglib2.0
        - attr
        - automake
        - gettext
        - autopoint
        - bison
        - dbus
        - gtk-doc-tools
        - libfuse-dev
        - libostree-dev
        - libarchive-dev
        - libcap-dev
        - libattr1-dev
        - libdw-dev
        - libelf-dev
        - python3-pyparsing
        - libjson-glib-dev
        - shared-mime-info
        - desktop-file-utils
        - libpolkit-agent-1-dev
        - libpolkit-gobject-1-dev
        - libseccomp-dev
        - libsoup2.4-dev
        - libsystemd-dev
        - libxml2-utils
        - libgpgme11-dev
        - gobject-introspection
        - libgirepository1.0-dev
        - libappstream-glib-dev
        - libdconf-dev
        - socat
        - libdbus-1-dev
      command:
        - git clone https://github.com/ostreedev/ostree.git
        - cd ostree
        - git checkout v2020.8
        - git submodule update --init
        - env NOCONFIGURE=1 ./autogen.sh
        - ./configure
        - make
        - make install
